language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-29.0.3
    - tools
    - android-29
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
        # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
 - chmod +x gradlew
script: 
    ./gradlew clean jacocoTestReport assembleDebug testDebug
after_success:
  - bash <(curl -s https://codecov.io/bash) 