language: android
dist: trusty
android:
  components:
    - build-tools-29.0.3
    - tools
    - android-29
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
        # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew test