object Versions {
    const val gradle = "4.0.1"
    const val kotlin = "1.3.70"
    const val timber = "4.7.1"
    const val lifecycle = "2.2.0"
    const val lifecycle_test = "2.1.0"
    const val coroutines = "1.3.8"
    const val koin = "2.0.1"
    const val viewpager2 = "1.0.0"
    const val material = "1.2.0-alpha04"
    const val mockito_kotlin = "2.2.0"
    const val mockito_kotlin_inline = "3.2.4"
    const val fragment_version = "1.2.0-rc01"
    const val nav_version = "2.2.0"
    const val ktor_client_android = "1.3.1"
    const val ktor_client_json = "1.3.1"
    const val okHttp_logging = "4.2.1"
    const val kittinunf_result = "2.3.0"
    const val paging_version = "3.0.0-alpha04"
    const val room = "2.3.0-alpha02"
    const val coil = "0.11.0"
}