object Versions {
   const val gradle = "3.5.0"
    const val kotlin = "1.3.50"
    const val timber = "4.7.1"
    const val lifecycle = "2.1.0"
    const val lifecycle_test = "2.1.0"
    const val coroutines = "1.3.0"
    const val koin = "2.0.1"
    const val viewpager2 = "1.0.0-rc01"
    const val material  = "1.2.0-alpha01"
    const val mockito_kotlin  = "2.1.0"
    const val fragment_version = "1.2.0-rc01"
    const val nav_version = "2.1.0"
    const val ktor_client_android = "1.3.0-beta-1"
    const val ktor_client_json = "1.3.0-beta-1"
}